### ISSUE TITLE
Not able to refresh the data app when updated the playstore app from 2.0.2 to 2.0.3.

### ISSUE THREAD

**Issue by dinesh-opg** [OnePointGlobal/OnePoint-Global-MySurveys-App-Android#47] opened 2017-12-29 06:41 UTC
When the user already installed the app and when he  updated to the latest playstore version.He is not able to refresh the data.
![issue](https://user-images.githubusercontent.com/26459785/34431048-58e2847e-ec91-11e7-8352-2ecb35c7c97c.png)

**Comment by NeerajOPG** [comment] 2018-01-02 06:03
Steps to replicate the issue : 
1. Install [MySurveys2.0_Version_2.0.2](http://apidev.1pt.mobi/apps/android/MySurveys2.0_Version_2.0.2_LIVE_SIGNED.apk)
2. Update MySurveys to 2.0.3 which is available on [PlayStore](https://play.google.com/store/apps/details?id=com.opg.my.surveys)
3 1. After updating from 2.0.2 to 2.0.3 ,Open My Surveys App

![screenshot_20180102-112724](https://user-images.githubusercontent.com/26483692/34475267-617981ce-efb0-11e7-8737-04fe00acd125.png)

 2. Do sync in MySurveys app
![screenshot_20180102-112736](https://user-images.githubusercontent.com/26483692/34475268-61ae43fa-efb0-11e7-8e5d-b14fa1bd4b69.png)

**Comment by NeerajOPG** [comment] 2018-01-02 06:52
The issue is fixed in 2.0.4.

**Comment by onepointpb** [comment] 2018-01-02 06:53
Verified the fix.

**Closed by onepointpb** 2018-01-02 06:53 UTC
Labels: bug
