### ISSUE TITLE
Performance of latest My Surveys app is slow when there are many co-ordinates attached to a particular address.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-MySurveys-App-Android#36] opened 2017-12-13 05:44 UTC
Performance of latest My Surveys app is slow when there are many co-ordinates attached to a particular address.

**Comment by NeerajOPG** [comment] 2017-12-14 10:46
The performance of the has increased now we are plotting the surveys which are visible to the user.
Still working on it to make it more faster.

**Comment by NeerajOPG** [comment] 2018-01-02 06:54
The issue is fixed in 2.0.3.

**Closed** 2019-09-20 11:57 UTC
Labels: enhancement, fixed
