### ISSUE TITLE
For tablet version of the app the "By Location" tab is not visible.

### ISSUE THREAD

**Issue by onepointpb** [OnePointGlobal/OnePoint-Global-MySurveys-App-Android#11] opened 2017-08-23 08:00 UTC
The panel contains few geofenced surveys. The Geofencing alert also working. But the tab is not visible.

**Comment by veereshms** [comment] 2017-08-23 11:03
When checked in toolkit location was missing from survey, now "By Location" tab is visible after adding a locations list to survey. But when locations list was missing we were getting geofencing alert for the survey.

**Comment by dinesh-opg** [comment] 2017-09-01 11:28
The thing is that might be some other panel may contain the same geofence survey with location .So you are getting the geofence alerts.If you still have some confusion or doubt please try to replicate the issue.If the api methods provide geofence survey it will start monitoring for those locations.Please check in the rest client.

**Comment by veereshms** [comment] 2017-09-07 11:15
As discussed we can't reproduce this issue and will close the issue now. Will be re-opened if it occurs again.

**Closed by veereshms** 2017-09-07 11:15 UTC
Labels: bug
